version: '3.1'

services:

  aqua:
    image: kanajin/aqua:latest
    restart: unless-stopped
    volumes:
      - "./config/application.properties:/aqua/config/application.properties"
      - "./data/db.sqlite:/aqua/data/db.sqlite"
      - "./data/diva_musiclist.json:/aqua/data/diva_musiclist.json"
    ports:
      - "80:80"
      - "22345:22345"
      - "8443:8443"