name: Aqua CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Rename and move
        run: cd /home/runner/work/Aqua-docker/Aqua-docker/target/ ; mv aqua-*-RELEASE.jar aqua.jar ; mv aqua-*/ aqua ; cd /home/runner/work/Aqua-docker/Aqua-docker/ ; mv docker-compose.yml ./target/aqua

      - name: Zip Release
        uses: thedoctor0/zip-release@master
        with:
          directory: '/home/runner/work/Aqua-docker/Aqua-docker/target/aqua/'
          type: 'zip'
          filename: 'datasource.zip'
          path: 'config data docker-compose.yml'

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
          touch release.txt
          [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
          [ $UPLOAD_WETRANSFER = true ] && echo "🔗 [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
          echo "::set-output name=status::success"

      - name: Upload Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "${{ steps.tag.outputs.release_tag }}"
          prerelease: false
          files: |
            /home/runner/work/Aqua-docker/Aqua-docker/target/aqua/datasource.zip
            /home/runner/work/Aqua-docker/Aqua-docker/target/aqua.jar

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: /home/runner/work/Aqua-docker/Aqua-docker/
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/aqua-server:latest
